# Introduction {#sec:introduction}
Over the period of 1990-1998, the field phase of the World Ocean Circulation Experiment (WOCE) was executed through international collaboration of about 30 countries [@thompson2001]. WOCE was a component of the World Climate Research Programme (WCRP), an international programme that helps to coordinate global climate research. WOCE was designed to address the inadequate coverage of the World Ocean, specifically in the Southern Hemisphere and during the winter months. 

A major Canadian contribution to WOCE and the subsequent CLIVAR (Climate Variability and Predictability) program was a dedicated field and modeling program in the Labrador Sea. The field component focused on the Atlantic Repeat Hydrography Line 7 West (AR7W) (Figure \@ref(fig:map)). The resulting research investigated the critical role of heat and freshwater fluxes from pack ice and coastal shelf water along the Canadian east coast on the oceanographic properties of the North Atlantic [@clarke2006; @lu2006; @lu2007].

Following WOCE, annual occupations of the AR7W line was continued by Fisheries and Ocean Canada through various short-term funding sources until the establishment of the [Atlantic Zone Off-Shelf Monitoring Program](https://www.bio.gc.ca/science/monitoring-monitorage/azomp-pmzao/azomp-pmzao-en.php) (AZOMP), in the late 2000s. AZOMP continues to occupy AR7W annually in support of the [Global Ocean Ship-based Hydrographic Investigations Program](http://www.go-ship.org/) (GO-SHIP), which brings together scientists with interests in physical oceanography, the carbon cycle, marine biogeochemistry and ecosystems, and other users and collectors of ocean interior data, and coordinates a network of globally sustained hydrographic sections as part of the global ocean/climate observing system including physical oceanography, the carbon cycle, marine biogeochemistry and ecosystems.
